export { default as Gungor } from './gungor'
export { default as Melih } from './melih'
export { default as Kubra } from './kubra'
export { default as Furkan } from './furkan'
export { default as Salih } from './salih'